### ISSUE TITLE
Padding on col-group

### ISSUE THREAD

**Issue by bradryanbice** [andri/fluidable#7] opened 2015-03-30 18:45 UTC
When nesting columns, there is an issue with laying out content. The first and last cells in a column group still have left and right padding (respectively) which pushes content inside of the container. 

Wouldn't it make more sense to eliminate these outside paddings on the first and last children of a col-group? I believe this is the default behavior of Bootstrap, for example. 

Is there a specific reason you did not include this, and what do you think about the nested columns issue and aligning nested content with un-nested content?

![screen shot 2015-03-30 at 1 45 22 pm](https://cloud.githubusercontent.com/assets/8323556/6903931/13d28be8-d6e3-11e4-9dd8-4d1fbc44032e.png)

**Comment by andri** [comment] 2015-04-01 21:39
Did you make sure to wrap your nested columns in a new col-group? Bootstrap requires you to do the same using an element with the class .row.

**Comment by bradryanbice** [comment] 2015-04-01 22:21
Yes, but there is no rule that eliminates the padding on first and last columns.

**Comment by andri** [comment] 2015-04-02 11:13
Yes thats by design, we use negative margins one the .col-group parent element like Bootstrap to achieve the same effect. This works much better when you have many columns and it gets hard to know what the first and last columns are. Here is an simple example that shows that nested columns align up just fine:

http://codepen.io/anon/pen/LEvdZZ

**Comment by bradryanbice** [comment] 2015-04-02 14:55
Just to be clear, I'm speaking of horizontal alignment, between to elements stacked on top of each other. As you can see in the image I've attached, they don't line up. Since every column has left and right padding, it doesn't matter if negative margins are applied, because the padding will build up from left to right on the left side, right to left on the right side.

For multiple rows, this will create a stair-stepping effect. 

Why aren't you eliminating the left padding on col-:first-child and the right padding on col-:last-child? I understand browser support, is that the only reason though?

![screen shot 2015-04-02 at 9 50 27 am](https://cloud.githubusercontent.com/assets/8323556/6966311/bbd04286-d91d-11e4-9d53-dbbc1c2b727f.png)

**Comment by andri** [comment] 2015-04-02 15:21
Gahh! :) This is not supposed to be like this, I will let you know when its fixed.

**Comment by andri** [comment] 2015-04-02 21:36
@bradryanbice This should be fixed now.

**Closed** 2015-04-02 21:37 UTC
